### ISSUE TITLE
映射地址转移到新地址问题

### ISSUE THREAD

**Issue by lijunhon** [0x01010110/corecfxs#3]
transfer.js里应该导入getNewCfxsIds而不是getIDs函数，这里好像写错了。

**Comment by lijunhon** [comment]
transferCfxs.js打错了

**Comment by 0x01010110** [comment]
兑换完的 cfxs, 在新旧合约的 id 是一样的, 所以用 getIDs 也是可以的

**Comment by lijunhon** [comment]
但是getIDs获取的数据不正常，应该是兑换后剩下的部分有问题的数据，getNewCfxsIds获取的数据是正常的。

**Comment by 0x01010110** [comment]
数据已经更新了, 你再更新代码就可以了
